name: test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12] # extend if needed

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "18.x"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Install SMART sandbox
        run: |
          git clone https://github.com/smart-on-fhir/smart-launcher-v2.git
          cd smart-launcher-v2
          git switch -c aa0f3b1 # Fix the version we use for the sandbox
          npm ci
          npm run build
      - name: Run tests
        run: |
          pytest tests/
        env:
          SANDBOX_DIR: ${{ github.workspace }}/smart-launcher-v2
